<?php

namespace Database\Seeders;

use App\Models\ZoonoticDisease;
use Illuminate\Database\Seeder;

class ZoonosisSeeder extends Seeder
{
    public function run()
    {
        $diseases = [
            // VIRAIS
            [
                'name' => 'Raiva',
                'slug' => 'raiva',
                'category' => 'viral',
                'causative_agent' => 'Vírus do gênero Lyssavirus (Rhabdoviridae)',
                'transmission' => 'Mordedura, arranhadura ou lambedura de animal infectado; contato da saliva com mucosas ou feridas.',
                'animal_symptoms' => 'Mudança de comportamento, agressividade, salivação excessiva, paralisia, dificuldade para engolir, convulsões.',
                'human_symptoms' => 'Febre, cefaleia, mal-estar, náuseas, dor no local da mordedura; progride para agitação, confusão, alucinações, hidrofobia, paralisia.',
                'incubation_period' => '2 a 60 dias (média 30 dias)',
                'prevention' => 'Vacinação anual de cães e gatos; evitar contato com animais silvestres; profilaxia pós-exposição (vacina + soro).',
                'treatment' => 'Não há tratamento curativo; profilaxia pós-exposição é essencial. Protocolo de Milwaukee em casos clínicos.',
                'is_notifiable' => true,
                'species_affected' => ['canine', 'feline', 'equine', 'bovine', 'wild_mammals'],
                'notes' => 'Taxa de letalidade próxima a 100% em humanos. Notificação obrigatória imediata.',
            ],
            [
                'name' => 'Leptospirose',
                'slug' => 'leptospirose',
                'category' => 'bacterial',
                'causative_agent' => 'Bactérias do gênero Leptospira',
                'transmission' => 'Contato com água ou solo contaminados por urina de animais infectados (principalmente roedores). Penetração cutânea ou mucosa.',
                'animal_symptoms' => 'Febre, icterícia, vômito, diarreia, poliúria, hemorragias, desidratação. Cães: forma ictérica ou hemorrágica.',
                'human_symptoms' => 'Febre alta, cefaleia, mialgia intensa (panturrilhas), icterícia, sufusão conjuntival, insuficiência renal.',
                'incubation_period' => '5 a 14 dias',
                'prevention' => 'Vacina v8/v10 para cães; controle de roedores; evitar contato com água de enchente; uso de EPIs.',
                'treatment' => 'Antibióticos (doxiciclina, penicilina, amoxicilina); suporte para insuficiência renal e hepática.',
                'is_notifiable' => true,
                'species_affected' => ['canine', 'feline', 'bovine', 'equine', 'rodents'],
                'notes' => 'Endêmica em áreas urbanas com enchentes. Associada a roedores.',
            ],
            [
                'name' => 'Toxoplasmose',
                'slug' => 'toxoplasmose',
                'category' => 'parasitic',
                'causative_agent' => 'Protozoário Toxoplasma gondii',
                'transmission' => 'Ingestão de carne crua ou mal cozida contendo cistos; contato com fezes de gatos infectados (oocistos); transmissão congênita.',
                'animal_symptoms' => 'Gatos: geralmente assintomáticos. Cães: febre, linfadenopatia, uveíte, pneumonia, sinais neurológicos.',
                'human_symptoms' => 'Geralmente assintomático em imunocompetentes; linfadenopatia, febre, cefaleia. Risco grave em gestantes (aborto, malformações) e imunossuprimidos.',
                'incubation_period' => '5 a 23 dias',
                'prevention' => 'Não oferecer carne crua a pets; evitar contato com fezes de gatos; higiene alimentar; gestantes evitarem limpeza de caixas de areia.',
                'treatment' => 'Clindamicina, pirimetamina + sulfadiazina, trimetoprim-sulfametoxazol.',
                'is_notifiable' => false,
                'species_affected' => ['feline', 'canine', 'bovine', 'ovine'],
                'notes' => 'Felinos são os hospedeiros definitivos. Alta prevalência mundial.',
            ],
            [
                'name' => 'Esporotricose',
                'slug' => 'esporotricose',
                'category' => 'fungal',
                'causative_agent' => 'Fungo Sporothrix schenckii',
                'transmission' => 'Inoculação cutânea através de arranhadura ou mordedura de gato infectado; contato com solo ou plantas contaminadas.',
                'animal_symptoms' => 'Gatos: lesões cutâneas ulceradas, nódulos, secreção purulenta, espirros, perda de peso. Cães: nódulos cutâneos.',
                'human_symptoms' => 'Lesão cutânea nodular no local da inoculação, linfangite, úlceras. Forma disseminada em imunossuprimidos.',
                'incubation_period' => '3 dias a 12 semanas',
                'prevention' => 'Uso de luvas ao tratar gatos com lesões; isolamento de animais infectados; castração e controle populacional de felinos.',
                'treatment' => 'Itraconazol, terbinafina, iodeto de potássio. Casos graves: anfotericina B.',
                'is_notifiable' => true,
                'species_affected' => ['feline', 'canine', 'equine'],
                'notes' => 'Emergente no Brasil. Transmissão felino-humano é a principal via. Notificação obrigatória em diversos municípios.',
            ],
            [
                'name' => 'Dermatofitose',
                'slug' => 'dermatofitose',
                'category' => 'fungal',
                'causative_agent' => 'Fungos dos gêneros Microsporum, Trichophyton e Epidermophyton',
                'transmission' => 'Contato direto com animal infectado; contato com fômites (escovas, camas, tosadores).',
                'animal_symptoms' => 'Áreas de alopecia circular, descamação, eritema, crostas. Prurido variável. Lesões na cabeça, orelhas e patas.',
                'human_symptoms' => 'Lesões anulares eritematosas com bordas elevadas e descamativas (tinea corporis). Prurido.',
                'incubation_period' => '1 a 3 semanas',
                'prevention' => 'Higiene ambiental; tratamento de animais infectados; evitar compartilhar objetos de uso animal.',
                'treatment' => 'Antifúngicos tópicos (cetoconazol, miconazol, terbinafina). Casos extensos: itraconazol, fluconazol, griseofulvina.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'equine', 'bovine', 'rodents'],
                'notes' => 'Zoonose ocupacional comum em veterinários e tratadores.',
            ],
            [
                'name' => 'Leishmaniose Visceral',
                'slug' => 'leishmaniose-visceral',
                'category' => 'parasitic',
                'causative_agent' => 'Protozoário Leishmania chagasi (infantum)',
                'transmission' => 'Picada do mosquito-palha (Lutzomyia longipalpis) infectado. Cães são o principal reservatório urbano.',
                'animal_symptoms' => 'Perda de peso, caquexia, febre, hepatoesplenomegalia, linfadenopatia, lesões cutâneas, onicogrifose, alopecia.',
                'human_symptoms' => 'Febre prolongada, perda de peso, hepatoesplenomegalia, anemia, pancitopenia, caquexia. Forma assintomática comum.',
                'incubation_period' => '10 dias a 2 anos (média 2-6 meses)',
                'prevention' => 'Uso de repelentes e telas; coleiras impregnadas com deltametrina em cães; eutanásia de cães soropositivos (controvérsia); vacinação canina.',
                'treatment' => 'Cães: miltefosina (aprovada no Brasil). Humanos: antimoniato de meglumina, anfotericina B, miltefosina.',
                'is_notifiable' => true,
                'species_affected' => ['canine', 'feline', 'equine', 'wild_canids'],
                'notes' => 'Expansão urbana no Brasil. Alta letalidade em humanos se não tratada. Cães são a principal fonte de infecção.',
            ],
            [
                'name' => 'Leishmaniose Tegumentar',
                'slug' => 'leishmaniose-tegumentar',
                'category' => 'parasitic',
                'causative_agent' => 'Protozoários Leishmania braziliensis, L. amazonensis, L. guyanensis',
                'transmission' => 'Picada do mosquito-palha (Lutzomyia spp.) infectado.',
                'animal_symptoms' => 'Úlceras cutâneas de bordas elevadas, nódulos, lesões mucosas. Cães e equinos podem ser reservatórios.',
                'human_symptoms' => 'Úlcera cutânea única ou múltipla, indolor, de bordas elevadas e fundo granuloso. Forma mucosa: lesões destrutivas em nariz, boca e faringe.',
                'incubation_period' => '2 semanas a 3 meses',
                'prevention' => 'Uso de repelentes e telas; evitar exposição em áreas endêmicas ao entardecer.',
                'treatment' => 'Antimoniato de meglumina, anfotericina B, pentamidina.',
                'is_notifiable' => true,
                'species_affected' => ['canine', 'equine', 'wild_mammals'],
                'notes' => 'Amazônia Legal concentra a maioria dos casos no Brasil.',
            ],
            [
                'name' => 'Ancilostomíase',
                'slug' => 'ancilostomiase',
                'category' => 'parasitic',
                'causative_agent' => 'Ancylostoma caninum, A. braziliense, A. duodenale',
                'transmission' => 'Penetração ativa de larvas através da pele; ingestão de larvas; transmissão transplacentária e transmamária em cães.',
                'animal_symptoms' => 'Anemia, diarreia escura, perda de peso, pelos opacos, fraqueza. Filhotes: anemia grave potencialmente fatal.',
                'human_symptoms' => 'Larva migrans cutânea (bicho-geográfico): lesões serpiginosas pruriginosas na pele.',
                'incubation_period' => 'Dias a semanas',
                'prevention' => 'Vermifugação regular de cães e gatos; recolhimento de fezes; evitar andar descalço em áreas contaminadas.',
                'treatment' => 'Animais: pamoato de pirantel, fenbendazol, ivermectina. Humanos: albendazol, tiabendazol tópico.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline'],
                'notes' => 'Alta prevalência em áreas de solo arenoso e quente. Principal causa de anemia em filhotes.',
            ],
            [
                'name' => 'Teníase / Cisticercose',
                'slug' => 'teniase-cisticercose',
                'category' => 'parasitic',
                'causative_agent' => 'Taenia solium (suíno) e Taenia saginata (bovino)',
                'transmission' => 'Ingestão de carne crua ou mal cozida contendo cisticercos. Cães podem atuar como hospedeiros intermediários de Echinococcus.',
                'animal_symptoms' => 'Cães com Echinococcus: geralmente assintomáticos. Suínos/bovinos: cisticercos em músculos.',
                'human_symptoms' => 'Teníase: dor abdominal, náuseas, perda de peso. Cisticercose: nódulos subcutâneos, convulsões (neurocisticercose).',
                'incubation_period' => '3 a 12 semanas (teníase)',
                'prevention' => 'Não oferecer carne crua a animais; cozimento adequado da carne; vermifugação; higiene das mãos.',
                'treatment' => 'Praziquantel, niclosamida. Neurocisticercose: albendazol + corticoides.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'bovine', 'swine'],
                'notes' => 'Neurocisticercose é uma das principais causas de epilepsia adquirida em países em desenvolvimento.',
            ],
            [
                'name' => 'Equinococose (Hidatidose)',
                'slug' => 'equinococose',
                'category' => 'parasitic',
                'causative_agent' => 'Echinococcus granulosus (forma cística), E. multilocularis (forma alveolar)',
                'transmission' => 'Ingestão de ovos eliminados nas fezes de cães infectados. Cães se infectam ao ingerir vísceras de ovinos/bovinos com cistos.',
                'animal_symptoms' => 'Cães: geralmente assintomáticos. Ovinos/bovinos: formação de cistos hidáticos em fígado e pulmões.',
                'human_symptoms' => 'Cistos hepáticos e pulmonares de crescimento lento. Dor abdominal, icterícia, tosse, dispneia. Ruptura pode causar choque anafilático.',
                'incubation_period' => 'Meses a anos',
                'prevention' => 'Vermifugação regular de cães; não alimentar cães com vísceras cruas; evitar contato com fezes de cães em áreas endêmicas.',
                'treatment' => 'Cirurgia, drenagem percutânea, albendazol.',
                'is_notifiable' => true,
                'species_affected' => ['canine', 'ovine', 'bovine', 'swine'],
                'notes' => 'Regiões de criação de ovinos são endêmicas (Sul do Brasil).',
            ],
            [
                'name' => 'Dirofilariose (Vermes do Coração)',
                'slug' => 'dirofilariose',
                'category' => 'parasitic',
                'causative_agent' => 'Dirofilaria immitis',
                'transmission' => 'Picada de mosquitos (Culex, Aedes, Anopheles) infectados com larvas do parasita.',
                'animal_symptoms' => 'Cães: tosse, intolerância ao exercício, dispneia, insuficiência cardíaca, caquexia. Gatos: tosse, vômito, síncope.',
                'human_symptoms' => 'Nódulo pulmonar solitário (granuloma). Geralmente assintomático; pode causar tosse e dor torácica.',
                'incubation_period' => '6 a 7 meses (até vermes adultos em cães)',
                'prevention' => 'Profilaxia mensal com ivermectina, milbemicina ou selamectina em cães; evitar exposição a mosquitos.',
                'treatment' => 'Cães: melarsomina (adulticida) + doxiciclina + ivermectina. Gatos: tratamento de suporte.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'wild_canids'],
                'notes' => 'Presente em áreas litorâneas do Brasil. Mosquitos são vetores obrigatórios.',
            ],
            [
                'name' => 'Giardíase',
                'slug' => 'giardiase',
                'category' => 'parasitic',
                'causative_agent' => 'Protozoário Giardia duodenalis (assemblages A, B, C, D, E, F)',
                'transmission' => 'Ingestão de cistos presentes em água ou alimentos contaminados com fezes; contato direto com animais infectados.',
                'animal_symptoms' => 'Diarreia aguda ou crônica, fezes pastosas a líquidas, esteatorreia, perda de peso, flatulência, vômitos.',
                'human_symptoms' => 'Diarreia aquosa, cólicas abdominais, náuseas, flatulência, desidratação. Pode ser assintomática.',
                'incubation_period' => '7 a 14 dias',
                'prevention' => 'Higiene ambiental; recolhimento de fezes; água filtrada ou fervida; lavagem das mãos.',
                'treatment' => 'Fenbendazol, metronidazol, secnidazol, nitazoxanida.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'bovine', 'rodents'],
                'notes' => 'Alta prevalência em canis e gatis. Assemblages A e B são potencialmente zoonóticas.',
            ],
            [
                'name' => 'Criptosporidiose',
                'slug' => 'criptosporidiose',
                'category' => 'parasitic',
                'causative_agent' => 'Protozoário Cryptosporidium parvum, C. hominis',
                'transmission' => 'Ingestão de oocistos em água ou alimentos contaminados com fezes. Altamente resistente à cloração.',
                'animal_symptoms' => 'Diarreia aquosa em filhotes, desidratação, anorexia, perda de peso. Bovinos: diarreia neonatal.',
                'human_symptoms' => 'Diarreia aquosa autolimitada, cólicas, desidratação. Grave em imunossuprimidos.',
                'incubation_period' => '5 a 7 dias',
                'prevention' => 'Higiene; água filtrada (filtros de 1 mícron); lavar frutas e vegetais; evitar contato com fezes de animais.',
                'treatment' => 'Nitazoxanida, suporte com fluidoterapia. Imunossuprimidos: tratamento prolongado.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'bovine', 'ovine', 'caprine'],
                'notes' => 'Causa comum de diarreia em bezerros. Oocistos resistentes ao cloro.',
            ],
            [
                'name' => 'Larva Migrans Visceral (Toxocaríase)',
                'slug' => 'larva-migrans-visceral',
                'category' => 'parasitic',
                'causative_agent' => 'Toxocara canis, Toxocara cati',
                'transmission' => 'Ingestão de ovos embrionados presentes em solo ou alimentos contaminados com fezes de cães/gatos.',
                'animal_symptoms' => 'Filhotes: distensão abdominal, diarreia, vômito, pelos opacos, retardo no crescimento. Pode causar obstrução intestinal.',
                'human_symptoms' => 'Febre, hepatoesplenomegalia, eosinofilia, tosse, dor abdominal. Larva migrans ocular: uveíte, perda visual.',
                'incubation_period' => 'Semanas a meses',
                'prevention' => 'Vermifugação regular de cães e gatos; recolhimento de fezes; higiene das mãos; evitar contato de crianças com solo contaminado.',
                'treatment' => 'Animais: pamoato de pirantel, fenbendazol. Humanos: albendazol, mebendazol, corticoides (casos oculares).',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline'],
                'notes' => 'Crianças são o grupo de maior risco. Ovos podem permanecer viáveis no solo por anos.',
            ],
            [
                'name' => 'Campilobacteriose',
                'slug' => 'campilobacteriose',
                'category' => 'bacterial',
                'causative_agent' => 'Campylobacter jejuni, C. coli, C. upsaliensis',
                'transmission' => 'Contato com fezes de animais infectados (cães, gatos, aves); ingestão de água ou alimentos contaminados; carne mal cozida.',
                'animal_symptoms' => 'Diarreia mucoide com sangue, febre, vômito. Filhotes e animais jovens são mais suscetíveis. Aves: geralmente assintomáticas.',
                'human_symptoms' => 'Diarreia aquosa ou sanguinolenta, febre, dor abdominal intensa, cefaleia. Pode evoluir para síndrome de Guillain-Barré.',
                'incubation_period' => '2 a 5 dias',
                'prevention' => 'Higiene ao manipular alimentos; cozimento adequado de carnes; lavar as mãos após contato com animais; recolhimento de fezes.',
                'treatment' => 'Geralmente autolimitado. Casos graves: azitromicina, eritromicina, fluoroquinolonas.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'avian', 'bovine', 'swine'],
                'notes' => 'Principal causa de diarreia bacteriana em humanos em muitos países.',
            ],
            [
                'name' => 'Salmonelose',
                'slug' => 'salmonelose',
                'category' => 'bacterial',
                'causative_agent' => 'Salmonella enterica (vários sorotipos: Typhimurium, Enteritidis)',
                'transmission' => 'Ingestão de alimentos contaminados (ovos, carnes, leite); contato com fezes de animais infectados (répteis, aves, cães).',
                'animal_symptoms' => 'Diarreia, vômito, febre, desidratação. Répteis e aves são frequentemente portadores assintomáticos. Filhotes: diarreia grave.',
                'human_symptoms' => 'Diarreia, febre, dor abdominal, náuseas, vômitos, cefaleia. Pode causar bacteremia e infecções focais.',
                'incubation_period' => '6 a 72 horas',
                'prevention' => 'Higiene ao manipular alimentos; lavar as mãos após manusear répteis, aves ou filhotes; cozimento adequado.',
                'treatment' => 'Geralmente autolimitado. Casos graves: fluoroquinolonas, ceftriaxona.',
                'is_notifiable' => true,
                'species_affected' => ['canine', 'feline', 'avian', 'reptile', 'bovine', 'swine'],
                'notes' => 'Répteis (tartarugas, iguanas) são fontes importantes de infecção em crianças.',
            ],
            [
                'name' => 'Febre da Mordedura de Rato (Sodoku)',
                'slug' => 'febre-mordedura-rato',
                'category' => 'bacterial',
                'causative_agent' => 'Streptobacillus moniliformis (América) / Spirillum minus (Ásia)',
                'transmission' => 'Mordedura ou arranhadura de roedores infectados (ratos, camundongos); ingestão de água ou alimentos contaminados.',
                'animal_symptoms' => 'Roedores: geralmente assintomáticos. Cães e gatos que caçam roedores podem ser portadores.',
                'human_symptoms' => 'Febre, calafrios, cefaleia, artralgia, exantema. Streptobacillus: poliartrite. Spirillum: lesão no local da mordida.',
                'incubation_period' => '3 a 21 dias',
                'prevention' => 'Controle de roedores; evitar contato direto com roedores silvestres; uso de luvas.',
                'treatment' => 'Penicilina G, amoxicilina, doxiciclina.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'rodents'],
                'notes' => 'Ocorre principalmente em áreas urbanas com infestação de roedores.',
            ],
            [
                'name' => 'Febre Q (Query Fever)',
                'slug' => 'febre-q',
                'category' => 'bacterial',
                'causative_agent' => 'Coxiella burnetii',
                'transmission' => 'Inalação de aerossóis contaminados com fezes, urina, leite ou produtos de parto de animais infectados (bovinos, ovinos, caprinos, cães).',
                'animal_symptoms' => 'Geralmente assintomáticos. Pode causar aborto, infertilidade, metrite em ruminantes. Cães: febre, letargia.',
                'human_symptoms' => 'Febre alta, cefaleia intensa, mialgia, pneumonia, hepatite. Fadiga crônica. Endocardite em casos crônicos.',
                'incubation_period' => '14 a 30 dias',
                'prevention' => 'Descarte seguro de dejetos animais; uso de EPIs em maternidades; pasteurização do leite.',
                'treatment' => 'Doxiciclina, hidroxicloroquina (casos crônicos).',
                'is_notifiable' => true,
                'species_affected' => ['bovine', 'ovine', 'caprine', 'canine', 'feline'],
                'notes' => 'Altamente resistente ao ambiente. Considerada potencial arma biológica.',
            ],
            [
                'name' => 'Brucelose',
                'slug' => 'brucelose',
                'category' => 'bacterial',
                'causative_agent' => 'Brucella canis, B. abortus, B. melitensis, B. suis',
                'transmission' => 'Contato com secreções genitais, abortos, leite, urina de animais infectados. B. canis: contato com cães infectados.',
                'animal_symptoms' => 'Aborto, infertilidade, epididimite, orquite. Cães: linfadenopatia, discospondilite, uveíte.',
                'human_symptoms' => 'Febre ondulante, sudorese noturna, fadiga, artralgia, hepatoesplenomegalia, linfadenopatia.',
                'incubation_period' => '1 a 6 semanas',
                'prevention' => 'Testagem e eliminação de animais positivos; vacinação de bovinos (B19, RB51); uso de EPIs; evitar consumo de leite cru.',
                'treatment' => 'Doxiciclina + rifampicina ou estreptomicina (humanos). Cães: tratamento difícil, longa duração.',
                'is_notifiable' => true,
                'species_affected' => ['canine', 'bovine', 'ovine', 'caprine', 'swine'],
                'notes' => 'Doença ocupacional em veterinários e trabalhadores rurais.',
            ],
            [
                'name' => 'Sarna Sarcóptica (Escabiose)',
                'slug' => 'sarna-sarcoptica',
                'category' => 'parasitic',
                'causative_agent' => 'Ácaro Sarcoptes scabiei var. canis',
                'transmission' => 'Contato direto com animal infectado; contato indireto através de fômites (camas, toalhas).',
                'animal_symptoms' => 'Prurido intenso, eritema, alopecia, crostas, escoriações. Orelhas, cotovelos e abdômen são áreas comuns.',
                'human_symptoms' => 'Prurido intenso, pápulas eritematosas, lesões de escoriação. Sarna norueguesa em imunossuprimidos.',
                'incubation_period' => '2 a 6 semanas (primeira infestação); 1 a 3 dias (reinfestação)',
                'prevention' => 'Isolamento e tratamento precoce de animais infestados; higiene ambiental; evitar contato com animais suspeitos.',
                'treatment' => 'Ivermectina, selamectina, milbemicina, moxidectina. Tratamento tópico: amitraz. Todos os contatos devem ser tratados.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'wild_canids'],
                'notes' => 'Altamente contagiosa. Transmissão ocorre mesmo antes dos sinais clínicos.',
            ],
            [
                'name' => 'Tungíase (Bicho-de-Pé)',
                'slug' => 'tungiase',
                'category' => 'parasitic',
                'causative_agent' => 'Pulga Tunga penetrans',
                'transmission' => 'Contato do pé com solo contaminado. Fêmeas grávidas penetram na pele.',
                'animal_symptoms' => 'Nódulos em patas, principalmente entre dedos. Cães: claudicação, lesões podais.',
                'human_symptoms' => 'Nódulo amarelado com ponto central escuro, geralmente nos pés. Dor, prurido, inflamação local. Infecção secundária.',
                'incubation_period' => 'Semanas',
                'prevention' => 'Calçados em áreas de solo arenoso; controle de pulgas em animais; higiene ambiental.',
                'treatment' => 'Remoção cirúrgica do parasita; antissépticos tópicos; ivermectina.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'swine', 'rodents'],
                'notes' => 'Comum em áreas rurais e praias. Associada à criação de suínos.',
            ],
            [
                'name' => 'Febre Amarela',
                'slug' => 'febre-amarela',
                'category' => 'viral',
                'causative_agent' => 'Vírus da Febre Amarela (Flavivirus, Flaviviridae)',
                'transmission' => 'Picada de mosquitos Aedes aegypti (urbano) / Haemagogus e Sabethes (silvestre). Primatas não humanos são reservatórios.',
                'animal_symptoms' => 'Primatas (macacos): febre, icterícia, hemorragia, morte súbita. Sinal de alerta para circulação viral.',
                'human_symptoms' => 'Febre, cefaleia, mialgia, náuseas. Forma grave: icterícia, hemorragias, insuficiência hepática e renal.',
                'incubation_period' => '3 a 6 dias',
                'prevention' => 'Vacinação (humanos); controle vetorial; notificação de epizootias em primatas; uso de repelentes.',
                'treatment' => 'Suporte intensivo. Não há antiviral específico.',
                'is_notifiable' => true,
                'species_affected' => ['non_human_primates', 'wild_mammals'],
                'notes' => 'Epizootias em primatas são sentinelas para circulação viral. Notificação obrigatória imediata.',
            ],
            [
                'name' => 'Cinomose',
                'slug' => 'cinomose',
                'category' => 'viral',
                'causative_agent' => 'Vírus da Cinomose Canina (Paramyxoviridae, Morbillivirus)',
                'transmission' => 'Aerossóis de secreções respiratórias, contato direto com animais infectados. Excreção viral prolongada.',
                'animal_symptoms' => 'Febre, secreção ocular e nasal, conjuntivite, pneumonia, diarreia, vômito, hiperqueratose de coxins, sinais neurológicos (tiques, convulsões).',
                'human_symptoms' => 'Não há evidências conclusivas de transmissão para humanos até o momento.',
                'incubation_period' => '7 a 14 dias',
                'prevention' => 'Vacinação (v8, v10, v11); isolamento de animais infectados; desinfecção ambiental.',
                'treatment' => 'Suporte (fluidos, antibióticos para infecções secundárias, anticonvulsivantes). Altamente letal.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'wild_canids', 'ferrets'],
                'notes' => 'Altamente contagiosa entre cães. Taxa de mortalidade alta. Vacinação é a única prevenção eficaz.',
            ],
            [
                'name' => 'Parvovirose Canina',
                'slug' => 'parvovirose',
                'category' => 'viral',
                'causative_agent' => 'Parvovírus Canino tipo 2 (CPV-2)',
                'transmission' => 'Contato direto com fezes de animais infectados; fômites; altamente resistente no ambiente.',
                'animal_symptoms' => 'Vômito intenso, diarreia hemorrágica, desidratação, febre, leucopenia, miocardite em filhotes.',
                'human_symptoms' => 'Não zoonótico.',
                'incubation_period' => '3 a 7 dias',
                'prevention' => 'Vacinação; isolamento de animais doentes; desinfecção com hipoclorito de sódio.',
                'treatment' => 'Suporte intensivo (fluidos, antieméticos, antibióticos, transfusão). Alta mortalidade sem tratamento.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'wild_canids'],
                'notes' => 'Vírus extremamente resistente no ambiente. Surtos comuns em canis e abrigos.',
            ],
            [
                'name' => 'Pasteurelose',
                'slug' => 'pasteurelose',
                'category' => 'bacterial',
                'causative_agent' => 'Pasteurella multocida, P. canis, P. dagmatis',
                'transmission' => 'Mordedura ou arranhadura de cães e principalmente gatos. Inalação de aerossóis (contato próximo).',
                'animal_symptoms' => 'Gatos e cães: frequentemente portadores assintomáticos na cavidade oral. Pneumonia em animais jovens ou imunossuprimidos.',
                'human_symptoms' => 'Celulite, abscesso no local da mordida, linfadenopatia, febre. Pode causar septicemia, pneumonia, osteomielite.',
                'incubation_period' => '3 a 8 horas (rápida progressão)',
                'prevention' => 'Lavagem imediata de feridas por mordeduras; atendimento médico precoce; profilaxia antibiótica em mordeduras.',
                'treatment' => 'Amoxicilina-clavulanato, doxiciclina, fluoroquinolonas.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'bovine', 'avian'],
                'notes' => 'Causa mais comum de infecção por mordedura de gatos.',
            ],
            [
                'name' => 'Capnofitose (Capnocytophaga)',
                'slug' => 'capnocytophaga',
                'category' => 'bacterial',
                'causative_agent' => 'Capnocytophaga canimorsus, C. cynodegmi',
                'transmission' => 'Mordedura, arranhadura ou lambedura de cães e gatos. Presente na flora oral de cães e gatos.',
                'animal_symptoms' => 'Portadores assintomáticos. Raramente causa doença em animais.',
                'human_symptoms' => 'Febre, calafrios, mialgia, sepse fulminante, choque séptico, púrpura, gangrena. Alta letalidade em imunossuprimidos (esplenectomizados).',
                'incubation_period' => '1 a 8 dias',
                'prevention' => 'Cuidado redobrado em imunossuprimidos (especialmente esplenectomizados) com mordeduras; lavagem de feridas.',
                'treatment' => 'Penicilina G, ampicilina, ceftriaxona, doxiciclina, fluoroquinolonas.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline'],
                'notes' => 'Infecção rara mas potencialmente fatal. Esplenectomizados são grupo de altíssimo risco.',
            ],
            [
                'name' => 'Hantavirose',
                'slug' => 'hantavirose',
                'category' => 'viral',
                'causative_agent' => 'Hantavírus (Bunyaviridae) - variantes Araraquara, Juquitiba, Castelo dos Sonhos',
                'transmission' => 'Inalação de aerossóis de urina, fezes ou saliva de roedores silvestres infectados (principalmente roedor-caxiinguelê - Necromys lasiurus).',
                'animal_symptoms' => 'Roedores: infecção persistente assintomática. Eliminam vírus na urina e fezes por toda a vida.',
                'human_symptoms' => 'Febre, cefaleia, mialgia intensa, dor lombar. Evolui rapidamente para insuficiência respiratória aguda (Síndrome Cardiopulmonar por Hantavírus).',
                'incubation_period' => '7 a 40 dias',
                'prevention' => 'Evitar contato com roedores silvestres; vedar frestas; armazenar grãos em recipientes fechados; limpeza de ambientes com proteção.',
                'treatment' => 'Suporte intensivo com oxigenação. Não há antiviral específico.',
                'is_notifiable' => true,
                'species_affected' => ['rodents', 'wild_mammals'],
                'notes' => 'Alta letalidade (40-50% no Brasil). Casos concentrados no Centro-Oeste e Sudeste.',
            ],
            [
                'name' => 'Febre Maculosa Brasileira',
                'slug' => 'febre-maculosa',
                'category' => 'bacterial',
                'causative_agent' => 'Rickettsia rickettsii',
                'transmission' => 'Picada do carrapato-estrela (Amblyomma sculptum, A. aureolatum) infectado. Capivaras e equídeos são reservatórios.',
                'animal_symptoms' => 'Cães e equinos: podem ser assintomáticos ou apresentar febre, anorexia, petéquias. Capivaras: reservatórios assintomáticos.',
                'human_symptoms' => 'Febre alta, cefaleia intensa, mialgia, exantema máculo-papular (inicia em punhos/tornozelos), gangrena, insuficiência múltipla.',
                'incubation_period' => '2 a 14 dias',
                'prevention' => 'Evitar áreas infestadas por carrapatos; uso de roupas claras e compridas; repelentes; inspeção de carrapatos após exposição.',
                'treatment' => 'Doxiciclina (precocemente, idealmente nos primeiros 3 dias de sintomas).',
                'is_notifiable' => true,
                'species_affected' => ['equine', 'canine', 'wild_mammals', 'birds'],
                'notes' => 'Letalidade acima de 50% sem tratamento. Associada a áreas de mata e capivaras.',
            ],
            [
                'name' => 'Doença de Lyme (Borreliose de Lyme)',
                'slug' => 'doenca-lyme',
                'category' => 'bacterial',
                'causative_agent' => 'Borreliella burgdorferi (complexo Borrelia burgdorferi sensu lato)',
                'transmission' => 'Picada de carrapatos do gênero Ixodes infectados.',
                'animal_symptoms' => 'Cães: febre, claudicação intermitente, artrite, linfadenopatia, glomerulonefrite. Gatos: raramente doentes.',
                'human_symptoms' => 'Eritema migratório (lesão em alvo), febre, cefaleia, artrite, mialgia. Manifestações neurológicas e cardíacas tardias.',
                'incubation_period' => '3 a 30 dias',
                'prevention' => 'Prevenção de carrapatos em animais (coleiras, comprimidos, spot-on); verificação de carrapatos após exposição; repelentes.',
                'treatment' => 'Doxiciclina, amoxicilina, cefuroxima, ceftriaxona (casos neurológicos).',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'equine', 'wild_mammals'],
                'notes' => 'Hemisfério Norte. No Brasil, casos raros e questionados. Existe forma semelhante (síndrome Baggio-Yoshinari).',
            ],
            [
                'name' => 'Coccidioidomicose (Febre do Vale)',
                'slug' => 'coccidioidomicose',
                'category' => 'fungal',
                'causative_agent' => 'Coccidioides immitis, C. posadasii',
                'transmission' => 'Inalação de artroconídios presentes em solo contaminado (regiões áridas e semiáridas).',
                'animal_symptoms' => 'Cães: tosse, febre, dispneia, claudicação (osteomielite), linfadenopatia, lesões cutâneas.',
                'human_symptoms' => 'Febre, tosse, dor torácica, eritema nodoso. Forma disseminada: ossos, SNC, pele.',
                'incubation_period' => '1 a 3 semanas',
                'prevention' => 'Evitar exposição a poeira em áreas endêmicas; umedecer o solo antes de escavar.',
                'treatment' => 'Fluconazol, itraconazol, anfotericina B (casos graves).',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'equine', 'wild_mammals'],
                'notes' => 'Regiões semiáridas do Brasil (Nordeste). Associada a escavações e obras.',
            ],
            [
                'name' => 'Criptococose',
                'slug' => 'criptococose',
                'category' => 'fungal',
                'causative_agent' => 'Cryptococcus neoformans, C. gattii',
                'transmission' => 'Inalação de leveduras presentes em fezes de pombos (C. neoformans) ou associadas a eucaliptos (C. gattii).',
                'animal_symptoms' => 'Gatos: lesões cutâneas (nariz, face), espirros, prostração, sinais neurológicos. Cães: sinais respiratórios e neurológicos.',
                'human_symptoms' => 'Meningite, pneumonia, lesões cutâneas. Principal causa de meningite fúngica em imunossuprimidos (HIV/AIDS).',
                'incubation_period' => 'Semanas a meses',
                'prevention' => 'Evitar acúmulo de fezes de pombos; uso de máscaras em limpeza de locais contaminados; isolamento de gatos infectados.',
                'treatment' => 'Anfotericina B + 5-fluorocitosina, fluconazol (manutenção).',
                'is_notifiable' => false,
                'species_affected' => ['feline', 'canine', 'avian'],
                'notes' => 'Gatos são os principais animais domésticos afetados. Associado a pombos e eucaliptos.',
            ],
            [
                'name' => 'Histoplasmose',
                'slug' => 'histoplasmose',
                'category' => 'fungal',
                'causative_agent' => 'Histoplasma capsulatum',
                'transmission' => 'Inalação de microconídios presentes em solo contaminado com fezes de morcegos e aves.',
                'animal_symptoms' => 'Cães e gatos: febre, perda de peso, tosse, diarreia, hepatoesplenomegalia, lesões cutâneas, linfadenopatia.',
                'human_symptoms' => 'Geralmente assintomático. Febre, tosse, dor torácica. Forma disseminada: hepatoesplenomegalia, lesões mucocutâneas.',
                'incubation_period' => '3 a 17 dias',
                'prevention' => 'Evitar contato com solo de cavernas, galpões com fezes de morcegos e aves; máscaras em locais de risco.',
                'treatment' => 'Itraconazol, anfotericina B (casos graves).',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'wild_mammals'],
                'notes' => 'Associado a cavernas, galinheiros, forros de casas com morcegos.',
            ],
            [
                'name' => 'Ornitose (Psitacose)',
                'slug' => 'ornitose',
                'category' => 'bacterial',
                'causative_agent' => 'Chlamydia psittaci',
                'transmission' => 'Inalação de poeira de fezes, penas ou secreções de aves infectadas (psitacídeos, pombos, perus).',
                'animal_symptoms' => 'Aves: conjuntivite, secreção nasal, diarreia, letargia, emagrecimento. Pode ser assintomática.',
                'human_symptoms' => 'Febre, cefaleia, mialgia, calafrios, pneumonia atípica. Tosse seca e prostração intensa.',
                'incubation_period' => '5 a 14 dias',
                'prevention' => 'Quarentena de aves recém-adquiridas; higiene de gaiolas; uso de máscaras ao limpar aviários; evitar superlotação.',
                'treatment' => 'Doxiciclina, tetraciclina, azitromicina, eritromicina.',
                'is_notifiable' => true,
                'species_affected' => ['avian', 'psittacidae'],
                'notes' => 'Doença ocupacional em tratadores de aves e funcionários de pet shops.',
            ],
            [
                'name' => 'Febre da Caspa de Rato (Febre de Haverhill)',
                'slug' => 'febre-caspa-rato',
                'category' => 'bacterial',
                'causative_agent' => 'Streptobacillus moniliformis',
                'transmission' => 'Ingestão de água ou alimentos contaminados com urina ou fezes de roedores; mordedura de rato.',
                'animal_symptoms' => 'Roedores: portadores assintomáticos.',
                'human_symptoms' => 'Febre, calafrios, vômito, artralgia intensa, exantema. Acometimento de grandes articulações.',
                'incubation_period' => '3 a 10 dias',
                'prevention' => 'Controle de roedores; higiene alimentar; armazenamento de alimentos em recipientes fechados.',
                'treatment' => 'Penicilina G, amoxicilina, doxiciclina.',
                'is_notifiable' => false,
                'species_affected' => ['rodents'],
                'notes' => 'Surtos associados a contaminação de alimentos por urina de roedores.',
            ],
            [
                'name' => 'Erisipela',
                'slug' => 'erisipela',
                'category' => 'bacterial',
                'causative_agent' => 'Erysipelothrix rhusiopathiae',
                'transmission' => 'Contato direto com carcaças, carne ou couro de animais infectados (suínos, peixes, aves). Inoculação cutânea.',
                'animal_symptoms' => 'Suínos: febre, lesões cutâneasrombiformes, artrite, endocardite. Aves e peixes: septicemia.',
                'human_symptoms' => 'Lesão cutânea erisipeloide no local da inoculação (dedos, mãos), eritema, edema, dor. Raramente septicemia e endocardite.',
                'incubation_period' => '1 a 4 dias',
                'prevention' => 'Uso de luvas ao manipular carcaças e carnes; cuidados com ferimentos.',
                'treatment' => 'Penicilina, amoxicilina, ciprofloxacino.',
                'is_notifiable' => false,
                'species_affected' => ['swine', 'avian', 'fish', 'ovine', 'bovine'],
                'notes' => 'Doença ocupacional em açougueiros, pescadores e veterinários.',
            ],
            [
                'name' => 'Estafilococose (Staphylococcus aureus resistente)',
                'slug' => 'estafilococose',
                'category' => 'bacterial',
                'causative_agent' => 'Staphylococcus aureus (incluindo MRSA), S. intermedius, S. pseudintermedius',
                'transmission' => 'Contato direto com animais infectados; fômites. MRSA de origem animal pode infectar humanos e vice-versa.',
                'animal_symptoms' => 'Infecções cutâneas (piodermite), abscessos, otite, infecções de feridas, infecções urinárias.',
                'human_symptoms' => 'Infecções cutâneas, abscessos, celulite, pneumonia, infecções de feridas cirúrgicas. MRSA: difícil tratamento.',
                'incubation_period' => 'Variável',
                'prevention' => 'Higiene das mãos após contato com animais; uso de luvas; cuidados com curativos; isolamento de MRSA.',
                'treatment' => 'Drenagem de abscessos, antibióticos conforme cultura e sensibilidade. MRSA: vancomicina, linezolida.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'feline', 'equine', 'bovine', 'swine', 'avian'],
                'notes' => 'Staphylococcus pseudintermedius é o principal estafilococo em cães. MRSA é preocupação em saúde pública.',
            ],
            [
                'name' => 'Carbúnculo (Antraz)',
                'slug' => 'carbunculo',
                'category' => 'bacterial',
                'causative_agent' => 'Bacillus anthracis',
                'transmission' => 'Contato com esporos em solo, carcaças ou produtos de origem animal (couro, lã, ossos). Inalação, ingestão ou inoculação.',
                'animal_symptoms' => 'Morte súbita, febre, hemorragias, edema subcutâneo, sangue não coagulado em orifícios naturais.',
                'human_symptoms' => 'Cutânea: úlcera necrótica com escara preta. Inalatória: pneumonia grave, mediastinite. Gastrointestinal: diarreia, vômito, febre.',
                'incubation_period' => '1 a 7 dias',
                'prevention' => 'Vacinação de animais em áreas endêmicas; incineração de carcaças suspeitas; EPIs ao manipular produtos de origem animal.',
                'treatment' => 'Ciprofloxacino, doxiciclina, penicilina. Antitoxina.',
                'is_notifiable' => true,
                'species_affected' => ['bovine', 'ovine', 'caprine', 'equine', 'swine', 'wild_mammals'],
                'notes' => 'Bioterrorismo. Esporos podem permanecer viáveis no solo por décadas. Notificação obrigatória imediata.',
            ],
            [
                'name' => 'Tétano',
                'slug' => 'tetanos',
                'category' => 'bacterial',
                'causative_agent' => 'Clostridium tetani',
                'transmission' => 'Contaminação de ferimentos com esporos presentes no solo, fezes ou poeira. Esporos germinam em feridas profundas e necróticas.',
                'animal_symptoms' => 'Rigidez muscular, espasmos, trismo (mandíbula travada), opistótono, hiperestesia. Equinos são mais suscetíveis.',
                'human_symptoms' => 'Trismo, rigidez muscular, espasmos, disfagia, opistótono. Insuficiência respiratória.',
                'incubation_period' => '3 a 21 dias',
                'prevention' => 'Vacinação de animais e humanos; limpeza adequada de ferimentos; soro antitetânico (profilaxia).',
                'treatment' => 'Soro antitetânico, limpeza da ferida, antibióticos (metronidazol), suporte respiratório, sedação.',
                'is_notifiable' => false,
                'species_affected' => ['equine', 'bovine', 'ovine', 'caprine', 'canine', 'feline'],
                'notes' => 'Esporos onipresentes no ambiente. Equinos são os mais suscetíveis entre os animais domésticos.',
            ],
            [
                'name' => 'Micoplasmose Hemotrópica (Micoplasmose Felina)',
                'slug' => 'micoplasmose-hemotropica',
                'category' => 'bacterial',
                'causative_agent' => 'Mycoplasma haemofelis, Candidatus Mycoplasma haemominutum (felinos); M. haemocanis (caninos)',
                'transmission' => 'Picada de pulgas e carrapatos; transmissão iatrogênica (transfusão); mordeduras.',
                'animal_symptoms' => 'Gatos: anemia hemolítica, febre, icterícia, letargia, esplenomegalia. Pode ser fatal em imunossuprimidos.',
                'human_symptoms' => 'Potencial zoonótico não estabelecido de forma conclusiva. Alguns relatos de infecção em humanos imunossuprimidos.',
                'incubation_period' => '2 a 34 dias',
                'prevention' => 'Controle de pulgas e carrapatos; testagem de doadores de sangue; isolamento de animais infectados.',
                'treatment' => 'Doxiciclina, marbofloxacino, enrofloxacino. Suporte com transfusão em anemia grave.',
                'is_notifiable' => false,
                'species_affected' => ['feline', 'canine'],
                'notes' => 'Também chamada de anemia infecciosa felina. Pulgas são o principal vetor.',
            ],
            [
                'name' => 'Listeriose',
                'slug' => 'listeriose',
                'category' => 'bacterial',
                'causative_agent' => 'Listeria monocytogenes',
                'transmission' => 'Ingestão de leite cru, queijos não pasteurizados, carne mal cozida ou vegetais contaminados. Animais: silagem contaminada.',
                'animal_symptoms' => 'Ruminantes: aborto, encefalite, septicemia, mastite. Cães e gatos: raramente doentes.',
                'human_symptoms' => 'Febre, mialgia, náuseas, diarreia. Gestantes: aborto, infecção neonatal. Imunossuprimidos: meningoencefalite, septicemia.',
                'incubation_period' => '1 a 4 semanas',
                'prevention' => 'Alimentação adequada (silagem de qualidade para ruminantes); pasteurização do leite; cozimento de alimentos.',
                'treatment' => 'Ampicilina + gentamicina, trimetoprim-sulfametoxazol.',
                'is_notifiable' => true,
                'species_affected' => ['bovine', 'ovine', 'caprine', 'canine', 'feline', 'avian'],
                'notes' => 'Altamente letal em recém-nascidos e imunossuprimidos. Associada a queijos não pasteurizados.',
            ],
            [
                'name' => 'Tuberculose Bovina (Micobacteriose)',
                'slug' => 'tuberculose-bovina',
                'category' => 'bacterial',
                'causative_agent' => 'Mycobacterium bovis (complexo Mycobacterium tuberculosis)',
                'transmission' => 'Inalação de aerossóis; ingestão de leite cru contaminado; contato direto com animais infectados.',
                'animal_symptoms' => 'Tosse crônica, emagrecimento, febre, linfadenopatia. Lesões granulomatosas em pulmões e linfonodos.',
                'human_symptoms' => 'Similar à tuberculose por M. tuberculosis: tosse, febre, sudorese noturna, perda de peso, hemoptise.',
                'incubation_period' => 'Semanas a anos',
                'prevention' => 'Teste tuberculínico em bovinos; abate sanitário de positivos; pasteurização do leite; vacinação (BCG não protege contra M. bovis).',
                'treatment' => 'Mesmo regime da TB (rifampicina, isoniazida, pirazinamida, etambutol). M. bovis é naturalmente resistente à pirazinamida.',
                'is_notifiable' => true,
                'species_affected' => ['bovine', 'caprine', 'swine', 'canine', 'feline', 'wild_mammals'],
                'notes' => 'PNCEBT (Programa Nacional de Erradicação da Brucelose e Tuberculose) no Brasil.',
            ],
            [
                'name' => 'Mormo',
                'slug' => 'mormo',
                'category' => 'bacterial',
                'causative_agent' => 'Burkholderia mallei',
                'transmission' => 'Contato direto com secreções nasais ou lesões cutâneas de equídeos infectados; ingestão de água ou alimentos contaminados.',
                'animal_symptoms' => 'Equinos: febre, secreção nasal purulenta, úlceras, nódulos linfáticos, lesões cutâneas, pneumonia. Alta letalidade.',
                'human_symptoms' => 'Febre, cefaleia, mialgia, abscessos cutâneos, pneumonia, septicemia. Alta letalidade.',
                'incubation_period' => '1 a 14 dias',
                'prevention' => 'Testagem de equídeos; sacrifício de animais positivos; quarentena; uso de EPIs; notificação obrigatória.',
                'treatment' => 'Ceftazidima, meropenem, doxiciclina, ciprofloxacino (combinações).',
                'is_notifiable' => true,
                'species_affected' => ['equine', 'asinine', 'mule'],
                'notes' => 'Doença erradicada em vários países. Reemergente no Brasil. Notificação obrigatória imediata.',
            ],
            [
                'name' => 'Encefalopatia Espongiforme Bovina (Vaca Louca)',
                'slug' => 'eeb',
                'category' => 'prion',
                'causative_agent' => 'Prion (Proteína priônica anormal - PrPSc)',
                'transmission' => 'Ingestão de farinha de carne e ossos contaminada com tecido nervoso de animais infectados (ruminação).',
                'animal_symptoms' => 'Bovinos: alteração de comportamento, hiperestesia, incoordenação, dificuldade de levantar, emagrecimento progressivo, morte.',
                'human_symptoms' => 'Variante da Doença de Creutzfeldt-Jakob (vDCJ): alterações psiquiátricas, demência progressiva, ataxia, mioclonias.',
                'incubation_period' => '2 a 8 anos (bovinos); anos a décadas (humanos)',
                'prevention' => 'Proibição de farinha de carne e ossos na alimentação de ruminantes; vigilância epidemiológica; remoção de material de risco específico.',
                'treatment' => 'Inexistente. Sempre fatal.',
                'is_notifiable' => true,
                'species_affected' => ['bovine', 'ovine', 'caprine', 'human'],
                'notes' => 'Brasil é classificado como país de risco insignificante pela OIE. Monitoramento constante.',
            ],
            [
                'name' => 'Influenza Aviária (Gripe Aviária)',
                'slug' => 'influenza-aviaria',
                'category' => 'viral',
                'causative_agent' => 'Vírus Influenza A subtipo H5N1, H7N9, H9N2 (Orthomyxoviridae)',
                'transmission' => 'Contato direto com aves infectadas (domésticas ou silvestres); secreções respiratórias e fezes. Potencial pandemia.',
                'animal_symptoms' => 'Aves: morte súbita, edema de cabeça e crista, cianose, secreção nasal, diarreia, queda na postura.',
                'human_symptoms' => 'Febre alta, tosse, dispneia, pneumonia viral grave, síndrome do desconforto respiratório agudo. Alta letalidade (H5N1: ~60%).',
                'incubation_period' => '2 a 8 dias',
                'prevention' => 'Vigilância em aves silvestres e domésticas; abate sanitário; biosseguridade em granjas; vacinação de aves; evitar contato com aves doentes.',
                'treatment' => 'Oseltamivir, zanamivir (antivirais). Suporte intensivo.',
                'is_notifiable' => true,
                'species_affected' => ['avian', 'swine', 'wild_birds'],
                'notes' => 'Vigilância intensificada no Brasil após casos na América do Sul. Potencial pandêmico.',
            ],
            [
                'name' => 'Febre Aftosa',
                'slug' => 'febre-aftosa',
                'category' => 'viral',
                'causative_agent' => 'Vírus da Febre Aftosa (Picornaviridae, Aphthovirus)',
                'transmission' => 'Contato direto, aerossóis, fômites, alimentos contaminados. Altamente contagiosa entre biungulados.',
                'animal_symptoms' => 'Febre, sialorreia, vesículas na língua, gengivas, lábios, espaço interdigital e tetos, claudicação, perda de peso.',
                'human_symptoms' => 'Raríssima em humanos. Febre, mal-estar, vesículas em mãos e boca (autolimitado).',
                'incubation_period' => '2 a 14 dias',
                'prevention' => 'Vacinação de bovinos e bubalinos; vigilância; abate sanitário; restrição de movimentação de animais.',
                'treatment' => 'Não há tratamento específico. Sacrifício de animais afetados é a política adotada.',
                'is_notifiable' => true,
                'species_affected' => ['bovine', 'swine', 'ovine', 'caprine', 'wild_ungulates'],
                'notes' => 'Brasil é maior exportador mundial de carne bovina. Manter status livre de aftosa é prioridade.',
            ],
            [
                'name' => 'Herpesvirose Equina',
                'slug' => 'herpesvirose-equina',
                'category' => 'viral',
                'causative_agent' => 'Herpesvírus Equino tipo 1 (EHV-1) e tipo 3 (EHV-3)',
                'transmission' => 'Contato direto, aerossóis; EHV-1 causa aborto e doença neurológica. EHV-3: exantema coital.',
                'animal_symptoms' => 'EHV-1: aborto, doença respiratória, mieloencefalopatia. EHV-3: lesões vesiculares em genitália.',
                'human_symptoms' => 'Não zoonótico.',
                'incubation_period' => '2 a 10 dias',
                'prevention' => 'Vacinação; isolamento de animais infectados; quarentena de novos animais.',
                'treatment' => 'Suporte; antivirais (aciclovir, valaciclovir) de eficácia limitada. Corticoides para forma neurológica.',
                'is_notifiable' => false,
                'species_affected' => ['equine', 'asinine'],
                'notes' => 'Forma neurológica (EHM) tem alta letalidade. Surtos em cavalos de esporte.',
            ],
            [
                'name' => 'Anemia Infecciosa Equina (AIE)',
                'slug' => 'anemia-infecciosa-equina',
                'category' => 'viral',
                'causative_agent' => 'Vírus da Anemia Infecciosa Equina (Retroviridae, Lentivirus)',
                'transmission' => 'Transmissão iatrogênica (agulhas, instrumentos cirúrgicos); picada de mutucas e moscas; transmissão transplacentária.',
                'animal_symptoms' => 'Febre, anemia, perda de peso, edema, petéquias, icterícia. Forma crônica: emagrecimento progressivo.',
                'human_symptoms' => 'Não zoonótico.',
                'incubation_period' => '7 a 35 dias',
                'prevention' => 'Testagem obrigatória (prova de Coggins); isolamento e eutanásia de positivos; uso de agulhas descartáveis.',
                'treatment' => 'Não há tratamento. Eutanásia é recomendada.',
                'is_notifiable' => true,
                'species_affected' => ['equine', 'asinine', 'mule'],
                'notes' => 'Doença de notificação obrigatória. Equinos positivos são permanentemente infectados.',
            ],
            [
                'name' => 'Hepatite por Ectima Contagioso (Dermatite Pustular)',
                'slug' => 'ectima-contagioso',
                'category' => 'viral',
                'causative_agent' => 'Vírus do Ectima Contagioso (Parapoxvirus)',
                'transmission' => 'Contato direto com lesões de ovinos e caprinos infectados; fômites.',
                'animal_symptoms' => 'Crostas e pústulas na boca, lábios, narinas e úbere de ovinos e caprinos. Cordeiros: dificuldade de mamar.',
                'human_symptoms' => 'Nódulo inflamatório localizado (geralmente nas mãos), eritema, crosta. Lesão autolimitada.',
                'incubation_period' => '3 a 7 dias',
                'prevention' => 'Luvas ao manusear ovinos e caprinos com lesões; vacinação do rebanho.',
                'treatment' => 'Autolimitado. Higiene local. Raramente requer intervenção.',
                'is_notifiable' => false,
                'species_affected' => ['ovine', 'caprine'],
                'notes' => 'Doença ocupacional em tratadores de ovinos e caprinos.',
            ],
            [
                'name' => 'Febre do Nilo Ocidental',
                'slug' => 'febre-nilo-ocidental',
                'category' => 'viral',
                'causative_agent' => 'Vírus do Nilo Ocidental (Flavivirus, Flaviviridae)',
                'transmission' => 'Picada de mosquitos Culex infectados. Aves são reservatórios amplificadores. Equídeos e humanos são hospedeiros acidentais.',
                'animal_symptoms' => 'Equinos: ataxia, andar em círculos, paralisia, convulsões, febre. Aves: morte súbita (corvos, gralhas).',
                'human_symptoms' => 'Geralmente assintomático. Febre, cefaleia, mialgia. Forma neuroinvasiva: meningite, encefalite, paralisia flácida.',
                'incubation_period' => '2 a 14 dias',
                'prevention' => 'Controle vetorial; vacinação de equinos; vigilância epizoótica em aves e equinos.',
                'treatment' => 'Suporte. Não há antiviral específico.',
                'is_notifiable' => true,
                'species_affected' => ['equine', 'avian', 'wild_birds'],
                'notes' => 'Presente nas Américas. Epizootias em aves e equinos precedem casos humanos.',
            ],
            [
                'name' => 'Hepatite Infecciosa Canina (Vírus de Rubarth)',
                'slug' => 'hepatite-infecciosa-canina',
                'category' => 'viral',
                'causative_agent' => 'Adenovírus Canino tipo 1 (CAV-1)',
                'transmission' => 'Contato com urina, fezes ou saliva de animais infectados. Excreção urinária prolongada.',
                'animal_symptoms' => 'Febre, apatia, vômito, dor abdominal, hepatite, edema de córnea ("olho azul"), coagulopatia. Forma peraguda fatal.',
                'human_symptoms' => 'Não zoonótico (CAV-1 não infecta humanos).',
                'incubation_period' => '4 a 9 dias',
                'prevention' => 'Vacinação v8/v10/v11. Vírus coberto pelas vacinas polivalentes.',
                'treatment' => 'Suporte intensivo (fluidos, transfusão em coagulopatias). Alta mortalidade em filhotes.',
                'is_notifiable' => false,
                'species_affected' => ['canine', 'wild_canids'],
                'notes' => 'Adenovírus canino tipo 2 (CAV-2) é usado em vacinas e também causa tosse dos canis.',
            ],
            [
                'name' => 'Panleucopenia Felina',
                'slug' => 'panleucopenia-felina',
                'category' => 'viral',
                'causative_agent' => 'Parvovírus Felino (FPV)',
                'transmission' => 'Contato direto com fezes, urina, secreções; fômites; transmissão transplacentária. Altamente resistente no ambiente.',
                'animal_symptoms' => 'Febre, vômito, diarreia, desidratação, leucopenia grave, prostração. Filhotes: morte súbita, síndrome cerebelar (in utero).',
                'human_symptoms' => 'Não zoonótico.',
                'incubation_period' => '4 a 7 dias',
                'prevention' => 'Vacinação (v3, v4, v5). Desinfecção com hipoclorito.',
                'treatment' => 'Suporte intensivo (fluidos, antieméticos, antibióticos, transfusão). Altamente letal sem tratamento.',
                'is_notifiable' => false,
                'species_affected' => ['feline', 'wild_felids'],
                'notes' => 'Altamente contagiosa entre felinos. Vírus resistente no ambiente.',
            ],
            [
                'name' => 'Leucemia Viral Felina (FeLV)',
                'slug' => 'felv',
                'category' => 'viral',
                'causative_agent' => 'Vírus da Leucemia Felina (Retroviridae, Gammaretrovirus)',
                'transmission' => 'Contato próximo (saliva, mordeduras, groomíng), transmissão vertical, transmissão por amamentação.',
                'animal_symptoms' => 'Imunossupressão, anemia, linfoma, leucemia, doenças secundárias recorrentes, infertilidade.',
                'human_symptoms' => 'Não zoonótico.',
                'incubation_period' => 'Semanas a meses',
                'prevention' => 'Vacinação; testagem; separação de gatos positivos e negativos; castração (reduz comportamento de risco).',
                'treatment' => 'Não há cura. Suporte, tratamento de infecções secundárias, quimioterapia para linfoma.',
                'is_notifiable' => false,
                'species_affected' => ['feline', 'wild_felids'],
                'notes' => 'Principal causa de morte de origem infecciosa em gatos domésticos.',
            ],
            [
                'name' => 'Imunodeficiência Viral Felina (FIV)',
                'slug' => 'fiv',
                'category' => 'viral',
                'causative_agent' => 'Vírus da Imunodeficiência Felina (Retroviridae, Lentivirus)',
                'transmission' => 'Mordeduras profundas (principalmente em gatos inteiros não castrados); transmissão vertical rara.',
                'animal_symptoms' => 'Imunossupressão progressiva, gengivite/estomatite crônica, infecções recorrentes, perda de peso, doenças neurológicas.',
                'human_symptoms' => 'Não zoonótico.',
                'incubation_period' => 'Meses a anos',
                'prevention' => 'Castração; manter gatos dentro de casa; testagem de novos animais; separação de gatos FIV+ e FIV-.',
                'treatment' => 'Não há cura. Suporte, controle de infecções secundárias, imunomoduladores, cuidados odontológicos.',
                'is_notifiable' => false,
                'species_affected' => ['feline', 'wild_felids'],
                'notes' => 'Semelhante ao HIV em humanos, mas específico para felinos. Não transmite para humanos.',
            ],
        ];

        foreach ($diseases as $disease) {
            ZoonoticDisease::firstOrCreate(
                ['slug' => $disease['slug']],
                $disease
            );
        }

        $this->command->info('Seeded ' . count($diseases) . ' zoonotic diseases.');
    }
}
