@startuml
!include _common.puml

title Fluxo de Prescricao com QR Code

|Veterinário|
start
:Selecionar Pet;
:Adicionar Medicamentos;
if (Substância Controlada?) then ([não])
else ([sim])
  :Validar ANVISA;
endif
|Sistema|
:Gerar Hash SHA-256 + QR;
|Veterinário|
:Gerar PDF Formatado;

split
  :Prescrição Salva;
  stop
split again
  |Sistema|
  :Notificar Tutor;
  |Tutor|
  :Receber PDF;
  |Público|
  :Escaneia QR Code;
  :Verificar /r/{hash};
endsplit
@enduml
