@startuml
!include _common.puml

title Fluxo de Odontologia

|Veterinário|
start
:Abrir Ficha Odontológica;
:Clicar no Dente;

|Sistema|
:Exibir Odontograma;

|Veterinário|
if (Procedimento Necessário?) then ([não])
  stop
else ([sim])
  split
    :Profilaxia (Raspagem);
  split again
    :Extração (Raio-X OBRIG);
  split again
    :Restauração / Canal;
  split again
    :Gengivectomia;
  endsplit

  |Tutor|
  :Autorizar Procedimento;

  |Veterinário|
  :Realizar Procedimento;
  :Prescrição Pós-OP;
  :Agendar Retorno;

  |Sistema|
  :Registrar na Timeline;
  stop
endif
@enduml
